### ISSUE TITLE
Future plans and fixes

### ISSUE THREAD

**Issue by TheNamlessGuy** [TheNamlessGuy/browser-redirector#3]
# TODO
- [ ] Deactivate an entire area at once
- [ ] Button for toggling collapse on all areas in both options and popup
- [ ] Button for (natural) sorting areas by name
- [ ] Search field for options/popup which filters based on area name and/or redirect alias
- [ ] (BUG) Have a default display value for empty area names in the popup

# Done
- [x] Automatic redirects
- [x] Manual swap redirects
- [x] Manual one-way redirects
- [x] Block access to certain URLs
- [x] (Soft) block access to certain URLs
